const IMAGE_MAP = {
  "Alpe du Knit Kit Pack": "/unlockables/alpe-du-knit-kit-pack.webp",
  "Alpine Slopes (Ski) Kits": "/unlockables/alpine-slopes-ski-kits.jpg",
  "Animal Print Pack": "/unlockables/animal-print-pack.webp",
  "April Fools 80's Kit": "/unlockables/april-fools-80-s-kit.webp",
  "April Fools 80s Paint Job": "/unlockables/april-fools-80s-paint-job.webp",
  "April Fools 80s Socks": "/unlockables/april-fools-80s-socks.webp",
  "Backwards Hat": "/unlockables/backwards-hat.webp",
  "Basic Kit 1": "/unlockables/basic-kit-1.jpg",
  "Basic Kit 2": "/unlockables/basic-kit-2.jpg",
  "Bell Javelin Helmet": "/unlockables/bell-javelin-helmet.webp",
  "Bike Packer Cap": "/unlockables/bike-packer-cap.webp",
  "Bike Packer Kit": "/unlockables/bike-packer-kit.webp",
  "Bike Packer Socks": "/unlockables/bike-packer-socks.webp",
  "Black Helmet": "/unlockables/black-helmet.webp",
  "Black Shoes": "/unlockables/black-shoes.webp",
  "Bont Shoes": "/unlockables/bont-shoes.webp",
  "Calories To Burn (Food) Socks": "/unlockables/calories-to-burn-food-socks.webp",
  "Camo Jersey pack": "/unlockables/camo-jersey-pack.jpg",
  "Classy Kits": "/unlockables/classy-kits.jpg",
  "Cool Tone Gloves": "/unlockables/cool-tone-gloves.webp",
  "Cute Socks": "/unlockables/cute-socks.webp",
  "Digital Camo Jersey pack": "/unlockables/digital-camo-jersey-pack.jpg",
  "Dino Power Cap & Socks": "/unlockables/dino-power-cap-socks.webp",
  "Dino Power Kit": "/unlockables/dino-power-kit.webp",
  "Dino Power Shoes": "/unlockables/dino-power-shoes.webp",
  "Dot Socks": "/unlockables/dot-socks.webp",
  "Dots Socks": "/unlockables/dots-socks.webp",
  "Flouro Kits": "/unlockables/flouro-kits.jpg",
  "Fluoro Gloves + Limar Air Speed White Helmet": "/unlockables/fluoro-gloves-limar-air-speed-white-helmet.webp",
  "Fun Shaped Glasses": "/unlockables/fun-shaped-glasses.webp",
  "Giro Aries Spherical Helmet": "/unlockables/giro-aries-spherical-helmet.webp",
  "Giro Imperial Shoes": "/unlockables/giro-imperial-shoes.webp",
  "Giro Synthe Helmet": "/unlockables/giro-synthe-helmet.webp",
  "Giro Vanquish Helmet": "/unlockables/giro-vanquish-helmet.webp",
  "Glasses Zwift #1": "/unlockables/glasses-zwift-1.webp",
  "Glasses Zwift #2": "/unlockables/glasses-zwift-2.webp",
  "Glove Pack Pattern": "/unlockables/glove-pack-pattern.webp",
  "Glove Pack Solid": "/unlockables/glove-pack-solid.webp",
  "Gloves": "/unlockables/gloves.webp",
  "Gravel Party Kit": "/unlockables/gravel-party-kit.webp",
  "Island Time Kit Pack": "/unlockables/island-time-kit-pack.webp",
  "Junk Food Kit Pack": "/unlockables/junk-food-kit-pack.webp",
  "Kask Elemento Helmet": "/unlockables/kask-elemento-helmet.webp",
  "La Z Claire Kit": "/unlockables/la-z-claire-kit.webp",
  "Level 100 Kit + Confetti Socks": "/unlockables/level-100-kit-confetti-socks.webp",
  "Level 15 jersey": "/unlockables/level-15-jersey.jpg",
  "Level 20 Jersey": "/unlockables/level-20-jersey.jpg",
  "Level 25 Kit": "/unlockables/level-25-kit.jpg",
  "Level 30 Kit": "/unlockables/level-30-kit.jpg",
  "Level 40 Kit": "/unlockables/level-40-kit.jpg",
  "Level 50 kit + Fire Socks": "/unlockables/level-50-kit-fire-socks.jpg",
  "Level 60 Kit": "/unlockables/level-60-kit.webp",
  "Level 70 Kit": "/unlockables/level-70-kit.webp",
  "Level 80 Kit": "/unlockables/level-80-kit.webp",
  "Level 90 Kit": "/unlockables/level-90-kit.webp",
  "Light Aero Helmet": "/unlockables/light-aero-helmet.webp",
  "London Tube Kit": "/unlockables/london-tube-kit.webp",
  "Makuri Blossoms Kit": "/unlockables/makuri-blossoms-kit.webp",
  "Mavic Shoes": "/unlockables/mavic-shoes.webp",
  "Mirage Cap": "/unlockables/mirage-cap.webp",
  "Mirage Helmet": "/unlockables/mirage-helmet.webp",
  "Mirage Kit": "/unlockables/mirage-kit.webp",
  "Mirage Shoes": "/unlockables/mirage-shoes.webp",
  "Mirage Socks": "/unlockables/mirage-socks.webp",
  "Modern Kit": "/unlockables/modern-kit.webp",
  "Monochrome Kit": "/unlockables/monochrome-kit.jpg",
  "Newsy (Paperboy) Cap": "/unlockables/newsy-paperboy-cap.webp",
  "Nimbl Feat Ultimate Shoes": "/unlockables/nimbl-feat-ultimate-shoes.webp",
  "Out of This World Kit": "/unlockables/out-of-this-world-kit.webp",
  "Out of This World Socks": "/unlockables/out-of-this-world-socks.webp",
  "Outfield Kit": "/unlockables/outfield-kit.webp",
  "Party Sock Pack": "/unlockables/party-sock-pack.webp",
  "Pattern Socks": "/unlockables/pattern-socks.webp",
  "Pop Art Shoes": "/unlockables/pop-art-shoes.webp",
  "Prism Kits": "/unlockables/prism-kits.jpg",
  "Rapha Pro Team Full Frame Sunglasses": "/unlockables/rapha-pro-team-full-frame-sunglasses.webp",
  "Rapha Pro Team Shoes": "/unlockables/rapha-pro-team-shoes.webp",
  "Rear View Mirror Glasses": "/unlockables/rear-view-mirror-glasses.webp",
  "Retro 80s Helmet": "/unlockables/retro-80s-helmet.webp",
  "Retro 80s Sunglasses (Oakley Eyeshades)": "/unlockables/retro-80s-sunglasses-oakley-eyeshades.webp",
  "S-Works Evade 3 Helmet": "/unlockables/s-works-evade-3-helmet.webp",
  "S-Works Evade Helmet": "/unlockables/s-works-evade-helmet.webp",
  "S-Works Shoes": "/unlockables/s-works-shoes.webp",
  "Scotty Squirrel Cap": "/unlockables/scotty-squirrel-cap.webp",
  "Scotty Squirrel Socks": "/unlockables/scotty-squirrel-socks.webp",
  "Skater/Bowl Helmet": "/unlockables/skater-bowl-helmet.webp",
  "Solid Color Kit Pack": "/unlockables/solid-color-kit-pack.webp",
  "Solid Socks": "/unlockables/solid-socks.webp",
  "Striped Socks": "/unlockables/striped-socks.webp",
  "Tortoise & The Hare Sock Pack": "/unlockables/tortoise-the-hare-sock-pack.webp",
  "Vintage Gloves": "/unlockables/vintage-gloves.webp",
  "Vintage Kit pack": "/unlockables/vintage-kit-pack.jpg",
  "Vintage Leather Shoes": "/unlockables/vintage-leather-shoes.webp",
  "Wolf Power Kit": "/unlockables/wolf-power-kit.webp",
  "Zwift Glasses #1": "/unlockables/zwift-glasses-1.webp",
  "Zwift Glasses #2 (Oakleys)": "/unlockables/zwift-glasses-2-oakleys.webp",
  "Zwift Oversize Glasses": "/unlockables/zwift-oversize-glasses.webp",
  "Zwift Rockstar Glasses": "/unlockables/zwift-rockstar-glasses.webp",
  "Zwift Vintage Riding Goggles": "/unlockables/zwift-vintage-riding-goggles.webp",
};

export default IMAGE_MAP;